version: '2'
services:
  mongo:
    image: 'mongo:3.2'
    container_name: 'infolis-mongo'
    volumes: 
      - '/etc/localtime:/etc/localtime:ro'
      - './data/mongodb:/data/db'
      - './backup:/backup'
    # for development
    ports:
      - '27018:27017'
    restart: always
  infolis-web:
    build: 'repo/infolis-web'
    image: 'infolis/infolis-web'
    container_name: 'infolis-web-app'
    depends_on:
      - 'mongo'
      - 'infolink'
    environment:
      MONGO_ADDR: 'infolis-mongo'
      MONGO_PORT: '27017'
      INFOLINK_ADDR: 'infolink'
      INFOLINK_PORT: '8080'
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config/infolis-web.coffee:/app/config.production.coffee'
      - './data/logs:/app/logs'
      # for development
      - './repo/infolis-web/node_modules:/app/node_modules'
      - './repo/infolis-web/src:/app/src'
      - './repo/infolis-web/data/infolis.tson:/app/data/infolis.tson'
      - './repo/infolis-web/public:/app/public'
      - './repo/infolis-web/views:/app/views'
      - './repo/infolis-web/src-client:/app/src-client'
  infolink:
    build: 'repo/infolink'
    image: 'infolis/infolink'
    container_name: 'infolink-app'
    tmpfs:
      - '/tmp/infolis:size=1G'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config/infolink.properties:/etc/infolis-config.properties'
      - './data/uploads:/infolis-files'
  # infolis-github:
  #   build: 'repo/infolis.github.io'
  #   container_name: 'infolis-github-app'
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - './config/infolis-github.yml:/site/_config-dev.yml'
